## Clear history
rm(list = ls(all = TRUE))
graphics.off()

## Intall and load packages
libraries = c("stats", "stockPortfolio", "tseries")
lapply(libraries, function(x) if (!(x %in% installed.packages())) {
  install.packages(x)
})
lapply(libraries, library, quietly = TRUE, character.only = TRUE)

## Get Data, Returns and residuals generated by an ARMA model
grEx1 = getReturns(c('C'), start='2004-01-01', end='2008-12-31')
returns = grEx1$R
residuals = resid(arima(returns, order = c(1,0,1)), na.action=na.exclude)

## Identify HQC function
HQIC = function(n.like, k, n) {
  2 * n.like + 2 * k * log(log(n))
}

## Use bic to test
n = length(grEx1)
q = 10
p = 0
hqic.arch = NA

for(i in 1 : q) {
  hqic.arch[i] = HQIC(garch(residuals, order = c(p, i))$n.likeli, i + 1, n)
}

## Results
arch.min = min(hqic.arch)
hqic.arch
which(hqic.arch == min(hqic.arch), arr.ind = TRUE)